version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    security_opt:
      - seccomp:unconfined